project_name: pkger

version: 2

before:
  hooks:
    - go mod tidy -compat=1.21

builds:
  -
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Tag}}

archives:
  -
    files:
      - README.md
      - LICENSE

nfpms:
  -
    vendor: MinIO Inc.
    homepage: https://github.com/minio/pkger
    maintainer: MinIO Development <dev@minio.io>
    description: Debian, RPMs and APKs for MinIO
    license: GNU Affero General Public License v3.0
    formats:
      - deb
      - rpm
